# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 16:49
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('welcome', ckeditor.fields.RichTextField(default=b'')),
                ('about', ckeditor.fields.RichTextField(default=b'')),
                ('services', ckeditor.fields.RichTextField(blank=True)),
                ('portfolio', ckeditor_uploader.fields.RichTextUploadingField(default=b'')),
                ('contact', ckeditor.fields.RichTextField(default=b'')),
            ],
        ),
    ]
